# Generated by Django 4.2.7 on 2023-12-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название Блюда')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена блюда')),
            ],
            options={
                'verbose_name': 'Меню и блюдо',
                'verbose_name_plural': 'Меню и блюда',
            },
        ),
        migrations.CreateModel(
            name='Zaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(default=0, upload_to='ZavIMG/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
