# Generated by Django 4.2.7 on 2023-12-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_menu_zaved_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaved',
            name='image',
            field=models.ImageField(default=0, upload_to='ZavIMG/<django.db.models.fields.CharField>/', verbose_name='Изображение'),
        ),
    ]
