# Generated by Django 4.2.7 on 2023-12-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_alter_zaved_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaved',
            name='image',
            field=models.ImageField(default=0, upload_to='media/ZavIMG/', verbose_name='Изображение'),
        ),
    ]
