# Generated by Django 4.2.7 on 2023-12-18 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_alter_zaved_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaved',
            name='image',
        ),
        migrations.CreateModel(
            name='ZavedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ZavIMG/', verbose_name='Изображение')),
                ('zaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_site.zaved')),
            ],
            options={
                'verbose_name': 'Изображение Заведения',
                'verbose_name_plural': 'Изображения Заведения',
            },
        ),
    ]
