# Generated by Django 4.2.7 on 2023-12-19 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_remove_zaved_image_zavedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaved_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_menu', models.TextField(verbose_name='Меню')),
                ('zaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='main_site.zaved')),
            ],
        ),
    ]
