# Generated by Django 4.2.7 on 2023-12-20 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_zaved_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZavedSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemaPhoto', models.ImageField(upload_to='ZavIMG/Schema/', verbose_name='Схема зала')),
                ('zaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='main_site.zaved')),
            ],
            options={
                'verbose_name': 'Схема зала',
                'verbose_name_plural': 'Схемы зала',
            },
        ),
    ]
