# Generated by Django 4.2.7 on 2023-12-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_zavedschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaved',
            name='type',
            field=models.TextField(default='null', verbose_name='Тип заведения'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='bookingTableZaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_tabel', models.IntegerField(verbose_name='Номер столика')),
                ('deposit_table', models.IntegerField(verbose_name='Депозит стола')),
                ('date', models.DateField(verbose_name='Дата брони стола')),
                ('time', models.TimeField(verbose_name='Время брони стола')),
                ('zaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='main_site.zaved')),
            ],
        ),
    ]
