# Generated by Django 4.2.7 on 2023-12-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_remove_zaved_description_zaved_adress_zaved_avr_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_t', models.DateField(verbose_name='Выбор даты')),
                ('time_t', models.TextField(verbose_name='Время')),
                ('count_g', models.IntegerField(verbose_name='Количество гостей')),
                ('disc', models.TextField(verbose_name='Пожелания к брони')),
                ('zaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_table', to='main_site.zaved')),
            ],
            options={
                'verbose_name': 'Бронь столов',
                'verbose_name_plural': 'бронирование стола',
            },
        ),
    ]
