# Generated by Django 4.2.7 on 2023-12-26 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_bookingtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('bis', models.TextField()),
                ('content', models.TextField()),
                ('is_good', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reting', to='main_site.zaved')),
            ],
        ),
    ]
