# Generated by Django 4.2.7 on 2023-12-28 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0013_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='')),
                ('zaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_photos', to='main_site.zaved')),
            ],
        ),
    ]
