# Generated by Django 4.2.7 on 2023-12-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_menuphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuphotos',
            name='photos',
            field=models.ImageField(upload_to='ZavIMG/Menu/', verbose_name='Меню'),
        ),
    ]
