# Generated by Django 4.2.7 on 2023-12-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0015_alter_menuphotos_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(verbose_name='Логин')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('name', models.TextField(default='noname', verbose_name='Имя')),
            ],
        ),
    ]
