# Generated by Django 4.2.7 on 2023-12-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_auth_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='book',
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='main_site.auth'),
        ),
    ]
